repos:
- repo: https://github.com/humitos/mirrors-autoflake
  rev: v1.2
  hooks:
  - id: autoflake

- repo: https://github.com/psf/black
  rev: stable
  hooks:
  - id: black
    language_version: python3.6

- repo: https://github.com/pre-commit/mirrors-isort
  rev: v4.3.21
  hooks:
  - id: isort
    additional_dependencies: [toml]